CXX = gcc
FLAGS = 
FILES = _test_bool.c
EXE = _test_bool 

exe: all
	@echo "Executing " $(EXE)
	./$(EXE)

all:
	@echo "Compiling"
	$(CXX) $(FLAGS) $(FILES) -o $(EXE)

clean:
	@echo "Cleaning current directory"
	rm *~ *.o

