CXX = gcc
FLAGS = 
FILES = main.c
EXE = _test_ll_2 

exe: all
	@echo "Executing " $(EXE)
	./$(EXE)

all:
	@echo "Compiling"
	$(CXX) $(FLAGS) $(FILES) -o $(EXE)

clean:
	@echo "Cleaning current directory"
	rm *~ *.o

